wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693857773.99327
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.17
      5: 0.15.5
      8:
      - 5
device:
  desc: null
  value: cuda:0
num_img:
  desc: null
  value: 48000
ratio:
  desc: null
  value: 0.8
epoch:
  desc: null
  value: 300
model_path:
  desc: null
  value: ./results/MLP_902_2/
input_data_path:
  desc: null
  value: ../../knolling_dataset/MLP_unstack_902/labels_box/
output_data_path:
  desc: null
  value: ../../knolling_dataset/MLP_unstack_902/labels_unstack/
learning_rate:
  desc: null
  value: 0.001
patience:
  desc: null
  value: 10
factor:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 64
output_size:
  desc: null
  value: 6
abort_learning:
  desc: null
  value: 20
set_dropout:
  desc: null
  value: 0.1
num_boxes:
  desc: null
  value: 5
project_name:
  desc: null
  value: zzz_MLP_unstack
wandb_flag:
  desc: null
  value: true
use_mse:
  desc: null
  value: true
use_scaler:
  desc: null
  value: false
fine-tuning:
  desc: null
  value: false
node_1:
  desc: null
  value: 128
node_2:
  desc: null
  value: 32
node_3:
  desc: null
  value: 8
