all_zero_target: 0
batch_size: 64
dropout_prob: 0
forward_expansion: 4
forwardtype: 2
high_dim_encoder: true
log_pth: data/log_avid-water-128/
lr: 0.0001
map_embed_d_dim: 32
max_seq_length: 10
model_params: 87458
noise_std: 0
num_attention_heads: 4
num_data:
- 800000
- 200000
num_layers: 4
pos_encoding_Flag: true
pre_trained: true
