all_steps: true
all_zero_target: 0
batch_size: 512
dropout_prob: 0
forward_expansion: 4
forwardtype: 1
high_dim_encoder: true
log_pth: data/devoted-terrain-29/
lr: 0.0001
map_embed_d_dim: 32
max_seq_length: 10
model_params: 87818
noise_std: 0
num_attention_heads: 4
num_data:
- 480000
- 120000
num_layers: 4
object_num: -1
pos_encoding_Flag: true
pre_trained: true
